# Generated by Django 2.0 on 2018-12-24 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('an', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Calendrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mois',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_jours', models.IntegerField()),
                ('premier_jour', models.IntegerField()),
                ('nom', models.CharField(max_length=20)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knokke.Annee')),
            ],
        ),
        migrations.AddField(
            model_name='annee',
            name='calendrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knokke.Calendrier'),
        ),
    ]
