# Generated by Django 2.0 on 2019-01-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knokke', '0002_auto_20190103_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mois',
            name='nb_jours',
        ),
        migrations.RemoveField(
            model_name='mois',
            name='premier_jour',
        ),
    ]
