# Generated by Django 2.0 on 2019-01-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knokke', '0003_auto_20190105_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendrier',
            name='jours_reserves',
            field=models.TextField(),
        ),
    ]
