# Generated by Django 2.0 on 2019-01-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knokke', '0005_auto_20190107_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='reduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('reduction_pourcent', models.IntegerField()),
                ('reduction_jours', models.IntegerField()),
            ],
        ),
    ]
