# Generated by Django 2.0 on 2019-01-13 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knokke', '0008_auto_20190112_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='prix',
            name='annee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='knokke.Annee'),
        ),
    ]
