# Generated by Django 2.0 on 2019-02-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knokke', '0009_prix_annee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nettoyage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.IntegerField(default=60)),
            ],
        ),
    ]
