from django.db import models
import calendar

class Calendrier(models.Model):
    nom=models.CharField(max_length=30)
    jours_reserves = models.TextField()

    def set_list(self, element):
        if self.jours_reserves:
            self.jours_reserves = self.jours_reserves + "," + element
        else:
            self.jours_reserves = element

    def get_list(self):
        if self.jours_reserves:
            return self.jours_reserves.split(",")
        else:
            None
    def delete_list(self, element):
    	if self.jours_reserves:
    		self.jours_reserves=self.jours_reserves.replace("," + element,'')

    def __str__(self):
    	return self.nom
    
class Annee(models.Model):
	an=models.IntegerField()
	calendrier=models.ForeignKey(Calendrier,on_delete=models.CASCADE)

	def __str__(self):
		return str(self.an)

class Mois(models.Model):
	nom=models.CharField(max_length=20)
	annee=models.ForeignKey(Annee,on_delete=models.CASCADE)

	def __str__(self):
		return self.nom


class Prix(models.Model):
	nom=models.CharField(max_length=20)
	annee=models.ForeignKey(Annee,on_delete=models.CASCADE,null=True)
	janvier_jour1=models.IntegerField(default=60)
	janvier_jour2=models.IntegerField(default=60)
	janvier_jour3=models.IntegerField(default=60)
	janvier_jour4=models.IntegerField(default=60)
	janvier_jour5=models.IntegerField(default=60)
	janvier_jour6=models.IntegerField(default=60)
	janvier_jour7=models.IntegerField(default=60)
	janvier_jour8=models.IntegerField(default=60)
	janvier_jour9=models.IntegerField(default=60)
	janvier_jour10=models.IntegerField(default=60)
	janvier_jour11=models.IntegerField(default=60)
	janvier_jour12=models.IntegerField(default=60)
	janvier_jour13=models.IntegerField(default=60)
	janvier_jour14=models.IntegerField(default=60)
	janvier_jour15=models.IntegerField(default=60)
	janvier_jour16=models.IntegerField(default=60)
	janvier_jour17=models.IntegerField(default=60)
	janvier_jour18=models.IntegerField(default=60)
	janvier_jour19=models.IntegerField(default=60)
	janvier_jour20=models.IntegerField(default=60)
	janvier_jour21=models.IntegerField(default=60)
	janvier_jour22=models.IntegerField(default=60)
	janvier_jour23=models.IntegerField(default=60)
	janvier_jour24=models.IntegerField(default=60)
	janvier_jour25=models.IntegerField(default=60)
	janvier_jour26=models.IntegerField(default=60)
	janvier_jour27=models.IntegerField(default=60)
	janvier_jour28=models.IntegerField(default=60)
	janvier_jour29=models.IntegerField(default=60)
	janvier_jour30=models.IntegerField(default=60)
	janvier_jour31=models.IntegerField(default=60)

	
	fevrier_jour1=models.IntegerField(default=60)
	fevrier_jour2=models.IntegerField(default=60)
	fevrier_jour3=models.IntegerField(default=60)
	fevrier_jour4=models.IntegerField(default=60)
	fevrier_jour5=models.IntegerField(default=60)
	fevrier_jour6=models.IntegerField(default=60)
	fevrier_jour7=models.IntegerField(default=60)
	fevrier_jour8=models.IntegerField(default=60)
	fevrier_jour9=models.IntegerField(default=60)
	fevrier_jour10=models.IntegerField(default=60)
	fevrier_jour11=models.IntegerField(default=60)
	fevrier_jour12=models.IntegerField(default=60)
	fevrier_jour13=models.IntegerField(default=60)
	fevrier_jour14=models.IntegerField(default=60)
	fevrier_jour15=models.IntegerField(default=60)
	fevrier_jour16=models.IntegerField(default=60)
	fevrier_jour17=models.IntegerField(default=60)
	fevrier_jour18=models.IntegerField(default=60)
	fevrier_jour19=models.IntegerField(default=60)
	fevrier_jour20=models.IntegerField(default=60)
	fevrier_jour21=models.IntegerField(default=60)
	fevrier_jour22=models.IntegerField(default=60)
	fevrier_jour23=models.IntegerField(default=60)
	fevrier_jour24=models.IntegerField(default=60)
	fevrier_jour25=models.IntegerField(default=60)
	fevrier_jour26=models.IntegerField(default=60)
	fevrier_jour27=models.IntegerField(default=60)
	fevrier_jour28=models.IntegerField(default=60)
	fevrier_jour29=models.IntegerField(default=60)
	

	
	mars_jour1=models.IntegerField(default=55)
	mars_jour2=models.IntegerField(default=70)
	mars_jour3=models.IntegerField(default=70)
	mars_jour4=models.IntegerField(default=70)
	mars_jour5=models.IntegerField(default=70)
	mars_jour6=models.IntegerField(default=70)
	mars_jour7=models.IntegerField(default=70)
	mars_jour8=models.IntegerField(default=70)
	mars_jour9=models.IntegerField(default=70)
	mars_jour10=models.IntegerField(default=70)
	mars_jour11=models.IntegerField(default=55)
	mars_jour12=models.IntegerField(default=55)
	mars_jour13=models.IntegerField(default=55)
	mars_jour14=models.IntegerField(default=55)
	mars_jour15=models.IntegerField(default=55)
	mars_jour16=models.IntegerField(default=55)
	mars_jour17=models.IntegerField(default=55)
	mars_jour18=models.IntegerField(default=55)
	mars_jour19=models.IntegerField(default=55)
	mars_jour20=models.IntegerField(default=55)
	mars_jour21=models.IntegerField(default=55)
	mars_jour22=models.IntegerField(default=55)
	mars_jour23=models.IntegerField(default=55)
	mars_jour24=models.IntegerField(default=55)
	mars_jour25=models.IntegerField(default=55)
	mars_jour26=models.IntegerField(default=55)
	mars_jour27=models.IntegerField(default=55)
	mars_jour28=models.IntegerField(default=55)
	mars_jour29=models.IntegerField(default=55)
	mars_jour30=models.IntegerField(default=55)
	mars_jour31=models.IntegerField(default=55)

	
	avril_jour1=models.IntegerField(default=66)
	avril_jour2=models.IntegerField(default=66)
	avril_jour3=models.IntegerField(default=66)
	avril_jour4=models.IntegerField(default=66)
	avril_jour5=models.IntegerField(default=66)
	avril_jour6=models.IntegerField(default=100)
	avril_jour7=models.IntegerField(default=100)
	avril_jour8=models.IntegerField(default=100)
	avril_jour9=models.IntegerField(default=100)
	avril_jour10=models.IntegerField(default=100)
	avril_jour11=models.IntegerField(default=100)
	avril_jour12=models.IntegerField(default=100)
	avril_jour13=models.IntegerField(default=100)
	avril_jour14=models.IntegerField(default=100)
	avril_jour15=models.IntegerField(default=100)
	avril_jour16=models.IntegerField(default=100)
	avril_jour17=models.IntegerField(default=100)
	avril_jour18=models.IntegerField(default=100)
	avril_jour19=models.IntegerField(default=100)
	avril_jour20=models.IntegerField(default=100)
	avril_jour21=models.IntegerField(default=100)
	avril_jour22=models.IntegerField(default=100)
	avril_jour23=models.IntegerField(default=66)
	avril_jour24=models.IntegerField(default=66)
	avril_jour25=models.IntegerField(default=66)
	avril_jour26=models.IntegerField(default=66)
	avril_jour27=models.IntegerField(default=66)
	avril_jour28=models.IntegerField(default=66)
	avril_jour29=models.IntegerField(default=66)
	avril_jour30=models.IntegerField(default=66)
	

	
	mai_jour1=models.IntegerField(default=66)
	mai_jour2=models.IntegerField(default=66)
	mai_jour3=models.IntegerField(default=66)
	mai_jour4=models.IntegerField(default=66)
	mai_jour5=models.IntegerField(default=66)
	mai_jour6=models.IntegerField(default=66)
	mai_jour7=models.IntegerField(default=66)
	mai_jour8=models.IntegerField(default=66)
	mai_jour9=models.IntegerField(default=66)
	mai_jour10=models.IntegerField(default=66)
	mai_jour11=models.IntegerField(default=66)
	mai_jour12=models.IntegerField(default=66)
	mai_jour13=models.IntegerField(default=66)
	mai_jour14=models.IntegerField(default=66)
	mai_jour15=models.IntegerField(default=66)
	mai_jour16=models.IntegerField(default=66)
	mai_jour17=models.IntegerField(default=66)
	mai_jour18=models.IntegerField(default=66)
	mai_jour19=models.IntegerField(default=66)
	mai_jour20=models.IntegerField(default=66)
	mai_jour21=models.IntegerField(default=66)
	mai_jour22=models.IntegerField(default=66)
	mai_jour23=models.IntegerField(default=66)
	mai_jour24=models.IntegerField(default=66)
	mai_jour25=models.IntegerField(default=66)
	mai_jour26=models.IntegerField(default=66)
	mai_jour27=models.IntegerField(default=66)
	mai_jour28=models.IntegerField(default=66)
	mai_jour29=models.IntegerField(default=66)
	mai_jour30=models.IntegerField(default=66)
	mai_jour31=models.IntegerField(default=66)

	
	juin_jour1=models.IntegerField(default=66)
	juin_jour2=models.IntegerField(default=66)
	juin_jour3=models.IntegerField(default=66)
	juin_jour4=models.IntegerField(default=66)
	juin_jour5=models.IntegerField(default=66)
	juin_jour6=models.IntegerField(default=66)
	juin_jour7=models.IntegerField(default=66)
	juin_jour8=models.IntegerField(default=66)
	juin_jour9=models.IntegerField(default=66)
	juin_jour10=models.IntegerField(default=66)
	juin_jour11=models.IntegerField(default=66)
	juin_jour12=models.IntegerField(default=66)
	juin_jour13=models.IntegerField(default=66)
	juin_jour14=models.IntegerField(default=66)
	juin_jour15=models.IntegerField(default=66)
	juin_jour16=models.IntegerField(default=66)
	juin_jour17=models.IntegerField(default=66)
	juin_jour18=models.IntegerField(default=66)
	juin_jour19=models.IntegerField(default=66)
	juin_jour20=models.IntegerField(default=66)
	juin_jour21=models.IntegerField(default=66)
	juin_jour22=models.IntegerField(default=66)
	juin_jour23=models.IntegerField(default=66)
	juin_jour24=models.IntegerField(default=66)
	juin_jour25=models.IntegerField(default=66)
	juin_jour26=models.IntegerField(default=66)
	juin_jour27=models.IntegerField(default=66)
	juin_jour28=models.IntegerField(default=66)
	juin_jour29=models.IntegerField(default=66)
	juin_jour30=models.IntegerField(default=66)
	

	
	juillet_jour1=models.IntegerField(default=100)
	juillet_jour2=models.IntegerField(default=100)
	juillet_jour3=models.IntegerField(default=100)
	juillet_jour4=models.IntegerField(default=100)
	juillet_jour5=models.IntegerField(default=100)
	juillet_jour6=models.IntegerField(default=100)
	juillet_jour7=models.IntegerField(default=100)
	juillet_jour8=models.IntegerField(default=100)
	juillet_jour9=models.IntegerField(default=100)
	juillet_jour10=models.IntegerField(default=100)
	juillet_jour11=models.IntegerField(default=100)
	juillet_jour12=models.IntegerField(default=100)
	juillet_jour13=models.IntegerField(default=100)
	juillet_jour14=models.IntegerField(default=100)
	juillet_jour15=models.IntegerField(default=100)
	juillet_jour16=models.IntegerField(default=100)
	juillet_jour17=models.IntegerField(default=100)
	juillet_jour18=models.IntegerField(default=100)
	juillet_jour19=models.IntegerField(default=100)
	juillet_jour20=models.IntegerField(default=100)
	juillet_jour21=models.IntegerField(default=100)
	juillet_jour22=models.IntegerField(default=100)
	juillet_jour23=models.IntegerField(default=100)
	juillet_jour24=models.IntegerField(default=100)
	juillet_jour25=models.IntegerField(default=100)
	juillet_jour26=models.IntegerField(default=100)
	juillet_jour27=models.IntegerField(default=100)
	juillet_jour28=models.IntegerField(default=100)
	juillet_jour29=models.IntegerField(default=100)
	juillet_jour30=models.IntegerField(default=100)
	juillet_jour31=models.IntegerField(default=100)

	
	aout_jour1=models.IntegerField(default=100)
	aout_jour2=models.IntegerField(default=100)
	aout_jour3=models.IntegerField(default=100)
	aout_jour4=models.IntegerField(default=100)
	aout_jour5=models.IntegerField(default=100)
	aout_jour6=models.IntegerField(default=100)
	aout_jour7=models.IntegerField(default=100)
	aout_jour8=models.IntegerField(default=100)
	aout_jour9=models.IntegerField(default=100)
	aout_jour10=models.IntegerField(default=100)
	aout_jour11=models.IntegerField(default=100)
	aout_jour12=models.IntegerField(default=100)
	aout_jour13=models.IntegerField(default=100)
	aout_jour14=models.IntegerField(default=100)
	aout_jour15=models.IntegerField(default=100)
	aout_jour16=models.IntegerField(default=100)
	aout_jour17=models.IntegerField(default=100)
	aout_jour18=models.IntegerField(default=100)
	aout_jour19=models.IntegerField(default=100)
	aout_jour20=models.IntegerField(default=100)
	aout_jour21=models.IntegerField(default=100)
	aout_jour22=models.IntegerField(default=100)
	aout_jour23=models.IntegerField(default=100)
	aout_jour24=models.IntegerField(default=100)
	aout_jour25=models.IntegerField(default=100)
	aout_jour26=models.IntegerField(default=100)
	aout_jour27=models.IntegerField(default=100)
	aout_jour28=models.IntegerField(default=100)
	aout_jour29=models.IntegerField(default=100)
	aout_jour30=models.IntegerField(default=100)
	aout_jour31=models.IntegerField(default=100)

	
	septembre_jour1=models.IntegerField(default=66)
	septembre_jour2=models.IntegerField(default=66)
	septembre_jour3=models.IntegerField(default=66)
	septembre_jour4=models.IntegerField(default=66)
	septembre_jour5=models.IntegerField(default=66)
	septembre_jour6=models.IntegerField(default=66)
	septembre_jour7=models.IntegerField(default=66)
	septembre_jour8=models.IntegerField(default=66)
	septembre_jour9=models.IntegerField(default=66)
	septembre_jour10=models.IntegerField(default=66)
	septembre_jour11=models.IntegerField(default=66)
	septembre_jour12=models.IntegerField(default=66)
	septembre_jour13=models.IntegerField(default=66)
	septembre_jour14=models.IntegerField(default=66)
	septembre_jour15=models.IntegerField(default=66)
	septembre_jour16=models.IntegerField(default=66)
	septembre_jour17=models.IntegerField(default=66)
	septembre_jour18=models.IntegerField(default=66)
	septembre_jour19=models.IntegerField(default=66)
	septembre_jour20=models.IntegerField(default=66)
	septembre_jour21=models.IntegerField(default=66)
	septembre_jour22=models.IntegerField(default=66)
	septembre_jour23=models.IntegerField(default=66)
	septembre_jour24=models.IntegerField(default=66)
	septembre_jour25=models.IntegerField(default=66)
	septembre_jour26=models.IntegerField(default=66)
	septembre_jour27=models.IntegerField(default=66)
	septembre_jour28=models.IntegerField(default=66)
	septembre_jour29=models.IntegerField(default=66)
	septembre_jour30=models.IntegerField(default=66)
	

	
	octobre_jour1=models.IntegerField(default=55)
	octobre_jour2=models.IntegerField(default=55)
	octobre_jour3=models.IntegerField(default=55)
	octobre_jour4=models.IntegerField(default=55)
	octobre_jour5=models.IntegerField(default=55)
	octobre_jour6=models.IntegerField(default=55)
	octobre_jour7=models.IntegerField(default=55)
	octobre_jour8=models.IntegerField(default=55)
	octobre_jour9=models.IntegerField(default=55)
	octobre_jour10=models.IntegerField(default=55)
	octobre_jour11=models.IntegerField(default=55)
	octobre_jour12=models.IntegerField(default=55)
	octobre_jour13=models.IntegerField(default=55)
	octobre_jour14=models.IntegerField(default=55)
	octobre_jour15=models.IntegerField(default=55)
	octobre_jour16=models.IntegerField(default=55)
	octobre_jour17=models.IntegerField(default=55)
	octobre_jour18=models.IntegerField(default=55)
	octobre_jour19=models.IntegerField(default=55)
	octobre_jour20=models.IntegerField(default=55)
	octobre_jour21=models.IntegerField(default=55)
	octobre_jour22=models.IntegerField(default=55)
	octobre_jour23=models.IntegerField(default=55)
	octobre_jour24=models.IntegerField(default=55)
	octobre_jour25=models.IntegerField(default=55)
	octobre_jour26=models.IntegerField(default=55)
	octobre_jour27=models.IntegerField(default=55)
	octobre_jour28=models.IntegerField(default=55)
	octobre_jour29=models.IntegerField(default=55)
	octobre_jour30=models.IntegerField(default=55)
	octobre_jour31=models.IntegerField(default=55)

	
	novembre_jour1=models.IntegerField(default=55)
	novembre_jour2=models.IntegerField(default=55)
	novembre_jour3=models.IntegerField(default=55)
	novembre_jour4=models.IntegerField(default=55)
	novembre_jour5=models.IntegerField(default=55)
	novembre_jour6=models.IntegerField(default=55)
	novembre_jour7=models.IntegerField(default=55)
	novembre_jour8=models.IntegerField(default=55)
	novembre_jour9=models.IntegerField(default=55)
	novembre_jour10=models.IntegerField(default=55)
	novembre_jour11=models.IntegerField(default=55)
	novembre_jour12=models.IntegerField(default=55)
	novembre_jour13=models.IntegerField(default=55)
	novembre_jour14=models.IntegerField(default=55)
	novembre_jour15=models.IntegerField(default=55)
	novembre_jour16=models.IntegerField(default=55)
	novembre_jour17=models.IntegerField(default=55)
	novembre_jour18=models.IntegerField(default=55)
	novembre_jour19=models.IntegerField(default=55)
	novembre_jour20=models.IntegerField(default=55)
	novembre_jour21=models.IntegerField(default=55)
	novembre_jour22=models.IntegerField(default=55)
	novembre_jour23=models.IntegerField(default=55)
	novembre_jour24=models.IntegerField(default=55)
	novembre_jour25=models.IntegerField(default=55)
	novembre_jour26=models.IntegerField(default=55)
	novembre_jour27=models.IntegerField(default=55)
	novembre_jour28=models.IntegerField(default=55)
	novembre_jour29=models.IntegerField(default=55)
	novembre_jour30=models.IntegerField(default=55)
	

	
	decembre_jour1=models.IntegerField(default=55)
	decembre_jour2=models.IntegerField(default=55)
	decembre_jour3=models.IntegerField(default=55)
	decembre_jour4=models.IntegerField(default=55)
	decembre_jour5=models.IntegerField(default=55)
	decembre_jour6=models.IntegerField(default=55)
	decembre_jour7=models.IntegerField(default=55)
	decembre_jour8=models.IntegerField(default=55)
	decembre_jour9=models.IntegerField(default=55)
	decembre_jour10=models.IntegerField(default=55)
	decembre_jour11=models.IntegerField(default=55)
	decembre_jour12=models.IntegerField(default=55)
	decembre_jour13=models.IntegerField(default=55)
	decembre_jour14=models.IntegerField(default=55)
	decembre_jour15=models.IntegerField(default=55)
	decembre_jour16=models.IntegerField(default=55)
	decembre_jour17=models.IntegerField(default=55)
	decembre_jour18=models.IntegerField(default=55)
	decembre_jour19=models.IntegerField(default=55)
	decembre_jour20=models.IntegerField(default=55)
	decembre_jour21=models.IntegerField(default=100)
	decembre_jour22=models.IntegerField(default=100)
	decembre_jour23=models.IntegerField(default=100)
	decembre_jour24=models.IntegerField(default=100)
	decembre_jour25=models.IntegerField(default=100)
	decembre_jour26=models.IntegerField(default=100)
	decembre_jour27=models.IntegerField(default=100)
	decembre_jour28=models.IntegerField(default=100)
	decembre_jour29=models.IntegerField(default=100)
	decembre_jour30=models.IntegerField(default=100)
	decembre_jour31=models.IntegerField(default=100)


	class Meta:
		verbose_name="Prix"

	def __str__(self):
		return self.nom

class reduction(models.Model):
	nom=models.CharField(max_length=20)
	reduction_pourcent=models.IntegerField()
	reduction_jours=models.IntegerField()

	class Meta:
		verbose_name="réduction"
		ordering = ['reduction_jours']
	def __str__(self):
		return self.nom

class Nettoyage(models.Model):
	prix=models.IntegerField(default=60)
	def __str__(self):
		return 'Nettoyage'